application: cs2021-final-project
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: latest

handlers:
- url: /templates/.css
  static_file: welcome.css
- url: /.*
  script: main.application


